# Generated by Django 2.1.15 on 2022-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.IntegerField(null=True, verbose_name='门')),
                ('date', models.CharField(max_length=40, null=True, verbose_name='时间')),
            ],
        ),
    ]
