# Generated by Django 2.1.15 on 2022-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getdata',
            name='id',
        ),
        migrations.AddField(
            model_name='getdata',
            name='date',
            field=models.IntegerField(default=2, primary_key=True, serialize=False, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
