# Generated by Django 2.1.15 on 2022-04-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetData', '0006_auto_20220430_1243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='getdata',
            table='sensor',
        ),
    ]
