# Generated by Django 2.1.15 on 2022-04-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetData', '0007_auto_20220430_1528'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='getdata',
            table='sensor_data',
        ),
    ]
